FROM php:7.2-apache
RUN rm -rf /var/www/html/*
COPY robots.txt /var/www/html/
COPY WHEOi6NVuu1TsjnBj66u.txt /var/www/html/
COPY index.html /var/www/html/
COPY auth.php /var/www/html/
RUN chmod 755 /var/www/html/*
